
# coding: utf-8

# In[1]:


### Script that chooses 40 random words from a word list (with replacement) ###


import random
import numpy

words = "TRAITOR INSERT IMMERSE WHOLESOME ENTERPRISE PROMINENT DOMESTIC HEROIC MAJESTIC TEMPERATE PUNCTURE ABUNDANCE PUNCTUAL TENANT VACANT TYRANT PROSPEROUS PERCEIVE DECEIT CONSIDERATION COMBINATION VENTILATION FRAGRANT ASSISTANCE SEIZE ORDEAL FATAL BETRAY DIVINITY ADOPT PROMPT MERCY INSPIRE ROGUE EXPENSE EMBRACE RECITE FERTILE BARREN ENTIRELY WEARY AVOID ADMISSION UNION DEPOSIT RESERVE CONVERT CONVEY AMBITION OBJECTION OBJECT ACQUIRE AQUAINTED OFFEND OPPRESS RESIGN BURDEN PRETENCE TRIFLE VAPOUR INVALID RETREAT COMMIT SACRIFICE PURPOSE DIGEST POULTRY COMRADE ENDEAVOUR WHOLLY ORIGIN MORAL CSERMON IDLE IDOL STOOP GRATE LINGER MERCHANT CONSTANT EMPIRE LIMIT PUBLIC ADVANCE HASTY FLEET LIBERTY BANISH ESTIMATE PROMOTE ENTIRE DISCONTENT EVIDENT FREQUENT EXPEL SATIN SOBER EXCLAIM PLUNGE ATTEMPT TEMPTATION HARBOUR CONTRIBUTE CONSUME JUSTICE CONTRAST VEIL LABOUR OBLIGE COMPEL SUSPECT GARMENT FOUNDATION ERRAND PLEDGE DIVINE PERMIT HUMBLE VAST CONFINE CONTRACT CONVICT DEVOTE INHABIT PASTURE LEA COMPOSITION PERIL PROFIT FLOURISH CREDIT CULTIVATE"


def testwords():
    wordlist = words.split()
    outcome = []
    
    
    for i in range(1, 41):
        outcome.append(random.randint(1, len(wordlist) + 1))
    
    
    for i in outcome:
        print(wordlist[i])

testwords();


# In[2]:


### Script that chooses 40 random words from a word list (without replacement) ###

import random
import numpy as np

words = "TRAITOR INSERT IMMERSE WHOLESOME ENTERPRISE PROMINENT DOMESTIC HEROIC MAJESTIC TEMPERATE PUNCTURE ABUNDANCE PUNCTUAL TENANT VACANT TYRANT PROSPEROUS PERCEIVE DECEIT CONSIDERATION COMBINATION VENTILATION FRAGRANT ASSISTANCE SEIZE ORDEAL FATAL BETRAY DIVINITY ADOPT PROMPT MERCY INSPIRE ROGUE EXPENSE EMBRACE RECITE FERTILE BARREN ENTIRELY WEARY AVOID ADMISSION UNION DEPOSIT RESERVE CONVERT CONVEY AMBITION OBJECTION OBJECT ACQUIRE AQUAINTED OFFEND OPPRESS RESIGN BURDEN PRETENCE TRIFLE VAPOUR INVALID RETREAT COMMIT SACRIFICE PURPOSE DIGEST POULTRY COMRADE ENDEAVOUR WHOLLY ORIGIN MORAL CSERMON IDLE IDOL STOOP GRATE LINGER MERCHANT CONSTANT EMPIRE LIMIT PUBLIC ADVANCE HASTY FLEET LIBERTY BANISH ESTIMATE PROMOTE ENTIRE DISCONTENT EVIDENT FREQUENT EXPEL SATIN SOBER EXCLAIM PLUNGE ATTEMPT TEMPTATION HARBOUR CONTRIBUTE CONSUME JUSTICE CONTRAST VEIL LABOUR OBLIGE COMPEL SUSPECT GARMENT FOUNDATION ERRAND PLEDGE DIVINE PERMIT HUMBLE VAST CONFINE CONTRACT CONVICT DEVOTE INHABIT PASTURE LEA COMPOSITION PERIL PROFIT FLOURISH CREDIT CULTIVATE"


def testwords():
    wordlist = words.split()
    outcome = np.random.choice(132, 40, replace = False)
    
    for i in outcome:
        print(wordlist[i])

testwords();

